spring.application.name=14-SESSION-BACKEND-CRUD

# H2 DB를 웹 브라우저에서 볼 수 있게 허용
spring.h2.console.enabled=true

# DB 접속 주소 설정
spring.datasource.url=jdbc:h2:file:./data/testdb
spring.datasource.username=sa
spring.datasource.password=

# JPA가 기존 데이터를 지우지 않도록 설정
spring.jpa.hibernate.ddl-auto=update
